"""
This script auto-analyzes every ABF in the data folder.
It also creates readme.md to show all images produced.
"""

import os
import sys
import glob
import datetime

sys.path.append("../src/")
import pyABFauto

PATH_HERE = os.path.abspath(os.path.dirname(__file__))
PATH_DATA = os.path.join(PATH_HERE, "data")
PATH_IMAGES = os.path.join(PATH_HERE, "data/swhlab")

def deleteOldImages():
    print("Deleting old images...")
    for imagePath in glob.glob(PATH_IMAGES+"/*.png"):
        print("  deleting", os.path.basename(imagePath))
        os.remove(imagePath)

def autoAnalyzeAbfs():
    print("Auto-analyzing ABFs...")
    pyABFauto.analyzeFolder(PATH_DATA)

def createReadme():
    md = "# Auto-Analysis Output\n\n"
    genDate = str(datetime.datetime.now().date())
    genTime = str(datetime.datetime.now().time()).split(".")[0]
    md += f"_This page was generated by [analyzeDataFolder.py](../analyzeDataFolder.py) on {genDate} at {genTime}_\n\n"
    for imagePath in glob.glob(PATH_IMAGES+"/*.png"):
        bn = os.path.basename(imagePath)
        md += f"### {bn}\n\n"
        md += f"[![](swhlab/{bn})](swhlab/{bn})\n\n"
    mdPath = os.path.join(PATH_DATA,"readme.md")
    with open(mdPath, 'w') as f:
        f.write(md)
    print("wrote", mdPath)

if __name__=="__main__":
    deleteOldImages()
    autoAnalyzeAbfs()
    createReadme()
    print("DONE")